# Generated by Django 2.0 on 2020-06-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20200603_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Marks',
            new_name='marks',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='name',
        ),
    ]
